import { GameEngine } from '../GameEngine';
import { Entity, Vector2, BuildingType, UnitType } from '../types';

export function getCategory(this: GameEngine, subType: string): string {
if (['SOLDIER', 'TESLA_TROOPER', 'ENGINEER', 'ATTACK_DOG', 'FLAK_TROOPER', 'BORIS', 'CRAZY_IVAN', 'DESOLATOR', 'TERRORIST', 'YURI', 'YURI_PRIME', 'GI', 'ROCKETEER', 'NAVY_SEAL', 'CHRONO_LEGIONNAIRE', 'TANYA', 'SNIPER', 'CHRONO_IVAN', 'CHRONO_COMMANDO', 'PSI_COMMANDO', 'SPY'].includes(subType)) return 'INFANTRY';
if (['TANK', 'HARVESTER', 'APOCALYPSE_TANK', 'V3_LAUNCHER', 'TERROR_DRONE', 'RHINO_TANK', 'MCV', 'ALLIED_MCV', 'FLAK_TRACK', 'KIROV_AIRSHIP', 'TESLA_TANK', 'SIEGE_CHOPPER', 'TYPHOON_SUB', 'SEA_SCORPION', 'GIANT_SQUID', 'DREADNOUGHT', 'GRIZZLY_TANK', 'IFV', 'MIRAGE_TANK', 'PRISM_TANK', 'ROBOT_TANK', 'BATTLE_FORTRESS', 'CHRONO_MINER', 'AMPHIBIOUS_TRANSPORT', 'DESTROYER', 'AEGIS_CRUISER', 'AIRCRAFT_CARRIER', 'DOLPHIN', 'HARRIER', 'BLACK_EAGLE', 'NIGHT_HAWK_TRANSPORT'].includes(subType)) return 'VEHICLES';
if (['SENTRY_GUN', 'TESLA_COIL', 'FLAK_CANNON', 'IRON_CURTAIN', 'NUCLEAR_SILO', 'SOVIET_WALL', 'PATRIOT_MISSILE', 'PILLBOX', 'PRISM_TOWER', 'GAP_GENERATOR', 'CHRONOSPHERE', 'WEATHER_DEVICE', 'ALLIED_WALL'].includes(subType)) return 'DEFENSE';
return 'BUILDINGS';
}
